apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app.kubernetes.io/name: kbird
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

data:
  bird.conf: |-
    {{- if .Values.config }} {{ .Values.config | nindent 4 }} {{ else }} {{ .Files.Get "etc/bird.conf" | nindent 4 }} {{ end }}
