apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: kbird
spec:
  selector:
    matchLabels:
      app: kbird
  template:
    metadata:
      labels:
        app: kbird
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
      - name: kbird
        image: mhristache/kbird
        imagePullPolicy: IfNotPresent
        args:
          - -c
          - /config/bird.conf
        tty: true
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - all
            add:
              - net_raw
      volumes:
        - name: config
          configMap:
            name: bird-config
            items:
              - path: bird.conf
                key: bird.conf
